version: '3.8'

services:
  # Anvil for local Ethereum testing
  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    container_name: anvil-contracts
    entrypoint: [
        "anvil",
        "--host", "0.0.0.0",
        "--port", "8545",
        "--accounts", "10",
        "--balance", "10000",
        "--gas-limit", "30000000",
        "--gas-price", "1000000000",
        "--block-time", "2",
        "--chain-id", "31337"
    ]
    ports:
      - "8545:8545"
    networks:
      - contract-network

networks:
  contract-network:
    driver: bridge