[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
]
fs_permissions = [{ access = "read-write", path = "./" }]

[rpc_endpoints]
l1 = "${L1_RPC_URL}"
l2 = "${L2_RPC_URL}"

#[etherscan]
#l1 = { key = "${ETHERSCAN_API_KEY}" }
#l2 = { key = "${OPTIMISTIC_ETHERSCAN_API_KEY}" }
