name: Contracts Tests

on:
  push:
    paths:
      - 'contracts/**'
  pull_request:
    paths:
      - 'contracts/**'

jobs:
  test:
    name: Run Forge Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: contracts

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: forge install

      - name: Run Forge tests
        run: forge test --verbosity 3
