name: Contracts Tests

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}-tests
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get changed files
        uses: technote-space/get-diff-action@v6.1.2
        id: git_diff
        with:
          PATTERNS: |
            .github/workflows/contracts-test.yml
            **/*.sol

      - name: Install Foundry
        if: env.GIT_DIFF
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install pinned dependencies
        if: env.GIT_DIFF
        working-directory: ./contracts
        run: |
          forge install OpenZeppelin/openzeppelin-contracts@v4.9.5
          forge install foundry-rs/forge-std

      - name: Run contract tests
        if: env.GIT_DIFF
        working-directory: ./contracts
        run: forge test -vvvv