name: Contracts Tests

on:
  push:
    paths:
      - 'contracts/**'
  pull_request:
    paths:
      - 'contracts/**'

jobs:
  test:
    name: Run Forge Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: contracts

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: latest

      - name: Install OpenZeppelin v4.9.5
        run: forge install OpenZeppelin/openzeppelin-contracts@v4.9.5 --no-commit

      - name: Install forge-std (latest)
        run: forge install foundry-rs/forge-std --no-commit --no-git

      - name: Run Forge tests
        run: forge test --verbosity 3
